import type { Metadata } from "next";
import AdminHeader from "@/components/admin/AdminHeader/AdminHeader";
import AdminNavigation from "@/components/admin/AdminNavigation/AdminNavigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full min-h-screen font-solid">
      <AdminHeader />
      <main className="w-full flex justify-between">
        <AdminNavigation />
        { children }
      </main>
    </div>
  );
}
