import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/ui/Header/Header";
import ThemeProvider from "@/components/ui/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <body className="min-h-full flex flex-col">
      <Header />
      {children}
    </body>
  );
}
