import type { Metadata } from "next";
import { Geist, Londrina_Sketch, Londrina_Solid } from "next/font/google";
import "../globals.css";
import ThemeProvider from "@/components/ui/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const londrinaSketch = Londrina_Sketch({
  variable: "--font-londrina-sketch",
  weight: "400",
});

const londrinaSolid = Londrina_Solid({
  variable: "--font-londrina-solid",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html
        suppressHydrationWarning
        lang="en"
        className={`${geistSans.variable} ${londrinaSketch.variable} ${londrinaSolid.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
